CrossBIM/Pages/DXFToIFC/DownLoad.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Xbim.Common.Geometry;
using Xbim.Ifc;
using Xbim.IO;
using Xbim.ModelGeometry.Scene;
using CrossBIMLib;

namespace CrossBIM.Pages.DXFToIFC
{
    public class DownLoadModel : PageModel
    {
        [BindProperty]
        public string IFCFileName { get; set; }
        [BindProperty]
        public string WexBIMUploadedFileUrl { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public DownLoadModel(IWebHostEnvironment _Hosting)
        {
            Hosting = _Hosting;
        }
        public void OnGet(string fileName)
        {
            IFCFileName = fileName; //fileName; //has Extension .ifc

            string wexBIMFileName = IFCFileName.Replace(".ifc", ".wexBIM"); //"CrossBIMBuilding2.wexBIM";

            var filePath = Path.Combine(Hosting.WebRootPath, "Uploads", IFCFileName);

            string WexBimFilePath = ConverIfcToWexBim(filePath);

            var uploadParams = new RawUploadParams()
            {
                // by default, ResourceType is already set to "raw"
                File = new FileDescription(WexBimFilePath),
                Folder = "",//Folder Name
                PublicId = wexBIMFileName  //File New Name
            };

            /*
            Account account = new Account(
                  "Cloud",//user name
                  "APIKey",
                  "APISecert");
            */

            Account account = _Cloudinary.GetCloudinaryAccount();
            Cloudinary cloudinary = new Cloudinary(account);

            var uploadResult = cloudinary.Upload(uploadParams);

            WexBIMUploadedFileUrl = uploadResult.SecureUrl.ToString();
            
        }
        public ActionResult OnPostDownloadFile()
        {
            return File($@"\Uploads\{IFCFileName}", "application/x-step", IFCFileName);
        }

        private static string ConverIfcToWexBim(string filePath)
        {
            //var filePath = @$"~/Uploads/{fileName}";

            var wexBimFullPath = "";

            using (var model = IfcStore.Open(filePath))
            {

                var context = new Xbim3DModelContext(model);

                context.CreateContext();

                wexBimFullPath = Path.ChangeExtension(filePath, "wexBIM");

                var wexBimFileName = Path.GetFileName(wexBimFullPath);

                //ConfigurationManager.AppSettings.Set("wexBIMFileName", wexBimFileName);
                //ConfigurationManager.AppSettings.Set("wexBIMFullPath", "~/Uploads/" + wexBimFileName);

                using (var wexBiMfile = System.IO.File.Create(wexBimFullPath))
                {
                    using (var wexBimBinaryWriter = new BinaryWriter(wexBiMfile))
                    {
                        model.SaveAsWexBim(wexBimBinaryWriter);
                        wexBimBinaryWriter.Close();
                    }
                    wexBiMfile.Close();
                }

            }
            return wexBimFullPath;
        }
    }
}

CrossBIM/Pages/DXFToIFC/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrossBIM.Pages.DXFToIFC
{
    public class IndexModel : PageModel
    {
        [BindProperty]
        public string ProjectName { get; set; }
        [BindProperty]
        public string ProjectUnits { get; set; }
        [BindProperty]
        public string Message { get; set; }
        [BindProperty]
        public string FootingStatus { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public IndexModel(IWebHostEnvironment hosting)
        {
            Hosting = hosting;
        }
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {

            var IFCFilePath = Path.Combine(Hosting.WebRootPath, "Uploads", $"{ProjectName}.ifc");

            if (System.IO.File.Exists(IFCFilePath))
            {
                Message = "Please Choose a unique name for your project";
                return Page();
            }

            if (ProjectName == null)
            {
                Message = "Please Choose a name for your project";
                return Page();
            }

            if(FootingStatus == "Yes")
            {
                return RedirectToPage("./IsoFootingBasicDetails", new
                {
                    projectName = ProjectName,
                    projectUnits = ProjectUnits
                });
            }
            else
            {
                return RedirectToPage("./StoreyBasicDetails", new
                {
                    projectName = ProjectName,
                    projectUnits = ProjectUnits
                });
            }
        }
    }
}

CrossBIM/Pages/DXFToIFC/IsoFootingBasicDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CrossBIM.ViewModelClasses;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using netDxf;

namespace CrossBIM.Pages.DXFToIFC
{
    public class IsoFootingBasicDetailsModel : PageModel
    {
        [BindProperty]
        public IFormFile RefFile { get; set; }
        [BindProperty]
        public ViewModelIsoFooting ViewModelIsoFooting { get; set; }
        [BindProperty]
        public string ProjectName { get; set; }
        [BindProperty]
        public string ProjectUnits { get; set; }
        [BindProperty]
        public string Message { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public IsoFootingBasicDetailsModel(IWebHostEnvironment hosting)
        {
            Hosting = hosting;
        }
        public void OnGet(string projectName, string projectUnits)
        {
            ProjectName = projectName;
            ProjectUnits = projectUnits;
        }
        public IActionResult OnPost()
        {
            List<string> IsolatedFootingLayersName;
            
            if (RefFile?.FileName != null)
            {

                var fileName = Path.GetFileName(RefFile.FileName);
                // Get New Path related to project
                ViewModelIsoFooting.DXFFilePath = Path.Combine(Hosting.WebRootPath, "Uploads", fileName);
                // Copy File To the New Path in WWWroot
                using (var newStream = new FileStream(ViewModelIsoFooting.DXFFilePath, FileMode.Create))
                {
                    RefFile.CopyTo(newStream);
                }

                DxfDocument dxfDocumentLoaded = DxfDocument.Load(ViewModelIsoFooting.DXFFilePath);

                IsolatedFootingLayersName = dxfDocumentLoaded.Layers.Names.ToList();
            }
            else
            {
                Message = "Please Upload Your DXF File!";
                return Page();
            }

            if (ViewModelIsoFooting.FootingNumberOfCategories < 0 ||
                ViewModelIsoFooting.StripsNumberOfCategories < 0)
            {
                Message = "Please Enter Correct Data!";
                return Page();
            }

            
             
            return RedirectToPage("./IsoFootingFullDetails", new
            {
                footingNumOfCategories = ViewModelIsoFooting.FootingNumberOfCategories,
                stripsNumofCategories = ViewModelIsoFooting.StripsNumberOfCategories,
                layersName = IsolatedFootingLayersName,
                filePath = ViewModelIsoFooting.DXFFilePath,
                projectName = ProjectName,
                projectUnits = ProjectUnits
            });
        }
    }
}

CrossBIM/Pages/DXFToIFC/IsoFootingFullDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CrossBIM.HelperClasses;
using CrossBIM.ViewModelClasses;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrossBIM.Pages.DXFToIFC
{
    public class IsoFootingFullDetailsModel : PageModel
    {
        [BindProperty]
        public ViewModelIsoFooting ViewModelIsoFooting { get; set; }
        [BindProperty]
        public ViewModelStoreys ViewModelStorey { get; set; } = new ViewModelStoreys();
        [BindProperty]
        public string ProjectName { get; set; }
        [BindProperty]
        public string ProjectUnits { get; set; }
        [BindProperty]
        public string IFCFileName { get; set; }
        [BindProperty]
        public int FootingNumberOfCategories { get; set; }
        [BindProperty]
        public int StripsNumberOfCategories { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public IsoFootingFullDetailsModel(IWebHostEnvironment hosting)
        {
            Hosting = hosting;
        }
        public void OnGet(int footingNumOfCategories,int stripsNumofCategories, List<string> layersName,string filePath,string projectName,string projectUnits)
        {
            FootingNumberOfCategories = footingNumOfCategories;
            StripsNumberOfCategories = stripsNumofCategories;
            ViewModelStorey.DXFLayersNames = layersName;
            ViewModelStorey.DXFFilePath = filePath;

            ProjectName = projectName;
            ProjectUnits = projectUnits;
        }
        public IActionResult OnPost()
        {

            //var FilePath = ViewModelStorey.DXFFilePath;

            var IFCFileName = $"{ProjectName}.ifc";//"First Building8-6.ifc";
            //var xmlFileName = $"{ProjectName}.ifcxml";

            ViewModelIsoFooting.FootingNumberOfCategories = FootingNumberOfCategories;
            ViewModelIsoFooting.StripsNumberOfCategories = StripsNumberOfCategories;

            var IFCFilePath = Path.Combine(Hosting.WebRootPath, "Uploads", IFCFileName);

            HelperFunctions.IFCForIsolatedFooting(ViewModelStorey.DXFFilePath, IFCFilePath, ViewModelIsoFooting, ProjectUnits);

            return RedirectToPage("./StoreyBasicDetails", new
            {
                status = true,
                IfcFileName = IFCFileName, //has Extension .ifc
                projectName = ProjectName, //the same name but without .ifc
                projectUnits = ProjectUnits
            });
        }
        
    }
}

CrossBIM/Pages/DXFToIFC/StoreyBasicDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CrossBIM.ViewModelClasses;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using netDxf;

namespace CrossBIM.Pages.DXFToIFC
{
    public class StoreyBasicDetailsModel : PageModel
    {
        [BindProperty]
        public string ProjectName { get; set; }
        [BindProperty]
        public string IFCFileName { get; set; }
        [BindProperty]
        public ViewModelStoreys ViewModelStorey { get; set; }
        [BindProperty]
        public bool Status { get; set; }
        [BindProperty]
        public IFormFile RefFile { get; set; }
        [BindProperty]
        public string ProjectUnits { get; set; }
        [BindProperty]
        public string Message { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public StoreyBasicDetailsModel(IWebHostEnvironment hosting)
        {
            Hosting = hosting;
        }
        public void OnGet(string projectName,string projectUnits, bool status,string IfcFileName)
        {
            Status = status;
            IFCFileName = IfcFileName; // used for download button //has Extension .ifc
            ProjectName = projectName;
            ProjectUnits = projectUnits;
        }
        public IActionResult OnPost()
        {
            if (RefFile?.FileName != null)
            {

                var fileName = Path.GetFileName(RefFile.FileName);
                // Get New Path related to project
                ViewModelStorey.DXFFilePath = Path.Combine(Hosting.WebRootPath, "Uploads", fileName);
                // Copy File To the New Path in WWWroot
                using (var newStream = new FileStream(ViewModelStorey.DXFFilePath, FileMode.Create))
                {
                    RefFile.CopyTo(newStream);
                }

                DxfDocument dxfDocumentLoaded = DxfDocument.Load(ViewModelStorey.DXFFilePath);
                ViewModelStorey.DXFLayersNames = dxfDocumentLoaded.Layers.Names.ToList();
            }
            else 
            {
                Message = "Please Upload Your DXF File!";
                return Page();
            }

            if (ViewModelStorey.Height <= 0 ||
                ViewModelStorey.NumOfRepetitions < 0 ||
                ViewModelStorey.SlabsNumberOfCategories < 0 ||
                ViewModelStorey.BeamsNumberOfCategories < 0 )
            {
                Message = "Please Enter Correct Data!";
                return Page();
            }

                return RedirectToPage("./StoreyFullDetails",
            new {

                beamsCategory = ViewModelStorey.BeamsNumberOfCategories,
                slabsCategory = ViewModelStorey.SlabsNumberOfCategories,
                layersNames = ViewModelStorey.DXFLayersNames,
                filePath = ViewModelStorey.DXFFilePath,
                storeyHeight = ViewModelStorey.Height,
                storeyElevation = ViewModelStorey.Elevation,
                NumOfRepetitions = ViewModelStorey.NumOfRepetitions,
                //viewModelStorey = ViewModelStorey,
                projectName = ProjectName,
                projectUnits = ProjectUnits
            });
        }
    }
}

CrossBIM/Pages/DXFToIFC/StoreyFullDetails.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CrossBIM.HelperClasses;
using CrossBIM.ViewModelClasses;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CrossBIM.Pages.DXFToIFC
{
    public class StoreyFullDetailsModel : PageModel
    {
        [BindProperty]
        public string ProjectName { get; set; }
        [BindProperty]
        public ViewModelBeams ViewModelBeam { get; set; }
        [BindProperty]
        public ViewModelSlabs ViewModelSlab { get; set; }
        [BindProperty]
        public ViewModelStoreys ViewModelStorey { get; set; } = new ViewModelStoreys();
        [BindProperty]
        public ViewModelColumns ViewModelColumn { get; set; }
        [BindProperty]
        public IFormFile RefFile { get; set; }
        [BindProperty]
        public int SlabsNumberOfCategories { get; set; }
        [BindProperty] 
        public int BeamsNumberOfCategories { get; set; }
        [BindProperty]
        public bool Status { get; set; }
        [BindProperty]
        public string ProjectUnits { get; set; }
        public IWebHostEnvironment Hosting { get; }
        public StoreyFullDetailsModel(IWebHostEnvironment hosting)
        {
            Hosting = hosting;
        }
        public void OnGet(int NumOfRepetitions, int beamsCategory, int slabsCategory, string projectName, List<string> layersNames, string filePath, double storeyHeight, double storeyElevation, string projectUnits)
        {
            ViewModelStorey.NumOfRepetitions = NumOfRepetitions;
            ViewModelStorey.Elevation = storeyElevation;
            ViewModelStorey.Height = storeyHeight;
            ViewModelStorey.SlabsNumberOfCategories = slabsCategory;
            ViewModelStorey.BeamsNumberOfCategories = beamsCategory;
            ViewModelStorey.DXFLayersNames = layersNames;
            ViewModelStorey.DXFFilePath = filePath;

            ProjectName = projectName;
            ProjectUnits = projectUnits;
        }
        //public void OnGet(string projectName,ViewModelStoreys viewModelStorey)
        //{
        //    ViewModelStorey = viewModelStorey;
        //    ProjectName = projectName;
        //}
        public IActionResult OnPost()
        {
            Status = true;// to show Covert to IFC button

            var IFCFileName = $"{ProjectName}.ifc";
            var xmlFileName = $"{ProjectName}.ifcxml";

            var IFCFilePath = Path.Combine(Hosting.WebRootPath, "Uploads", IFCFileName);

            HelperFunctions.GetIFCFile(ViewModelStorey.DXFFilePath, IFCFilePath, ViewModelBeam, ViewModelSlab, ViewModelColumn, ViewModelStorey,ProjectUnits);
            /*
            // To Solve Error The process cannot access the file because it is being used by another process
            System.GC.Collect();
            System.GC.WaitForPendingFinalizers();

            if (System.IO.File.Exists(fullPath))
                System.IO.File.Delete(fullPath);
            */
            return RedirectToPage("./StoreyBasicDetails", new
            {
                IfcFileName = IFCFileName, //has Extension .ifc
                projectName = ProjectName, //the same name but without .ifc
                status = Status,
                projectUnits = ProjectUnits
            });
        }
        
    }
    
}

CrossBIM/Pages/DXFToIFC/DownLoad.cshtml
@page
@model CrossBIM.Pages.DXFToIFC.DownLoadModel
@{
}


@*<div class="row" style="margin: auto;width:80%">*@

@*<h3 class="mt-3 container">Download IFC File</h3>
    <hr class="container" />

    <div class="col-md-4 container">
        <form method="post" enctype="multipart/form-data">
            <input asp-for="IFCFileName" hidden />
            <div class="form-group">
                <button type="submit" asp-page-handler="DownloadFile" class="btn btn-info">
                    <i class="fa fa-cloud-download fa-fw"></i> Download IFC
                </button>
            </div>
        </form>
    </div>*@
@*</div>*@

<!DOCTYPE html>
<html>
<head>
    <title>xViewer</title>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">

    <script type="text/javascript" src="~/Viewer/gl-matrix.js"></script>
    <script type="text/javascript" src="~/Viewer/jquery.js"></script>
    <script type="text/javascript" src="~/Viewer/webgl-utils.js"></script>

    <script type="text/javascript" src="~/Viewer/xbim-product-type.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-state.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-shaders.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-model-geometry.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-model-handle.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-binary-reader.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-triangulated-shape.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/xbim-viewer.debug.js"></script>

    <script type="text/javascript" src="~/Viewer/XBIM/xbim-viewer.debug.bundle.js"></script>
    <script type="text/javascript" src="~/Viewer/XBIM/NavigationCube/xbim-navigation-cube-shaders.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/XBIM/NavigationCube/xbim-navigation-cube.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/XBIM/NavigationCube/xbim-navigation-cube-textures.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/XBIM/NavigationHome/xbim-navigation-home-textures.debug.js"></script>
    <script type="text/javascript" src="~/Viewer/XBIM/NavigationHome/xbim-navigation-home.debug.js"></script>

    <style>

        html, body {
            height: 100%;
            padding: 0;
            margin: 0;
        }

        canvas {
            display: block;
            border: none;
            margin-left: auto;
            margin-right: auto;
            width: 100%;
            height: 100%;
        }
    </style>
</head>
<body>

    <div class="DownloadContainer">
        <div class="container">
            <div class="col-md-4 pt-3">
                <form method="post" enctype="multipart/form-data">
                    <input asp-for="IFCFileName" hidden />
                    <div class="form-group" style="margin:0">
                        <button type="submit" asp-page-handler="DownloadFile" class="btn btn-info">
                            <i class="fa fa-cloud-download fa-fw"></i> Download IFC
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="content">
        <canvas id="viewer" width="500" height="500"></canvas>
        <script type="text/javascript">
                var viewer = new xViewer('viewer');
                viewer.load("@Model.WexBIMUploadedFileUrl");
                /*viewer.load("https://res.cloudinary.com/amostafah/raw/upload/v1623659457/CrossBIM/firstProject%20%2815%29.wexBIM");*/
               /* viewer.load('../data/SampleHouse.wexbim');*/
                @*viewer.load('@System.Configuration.ConfigurationManager.AppSettings["wexBIMFullPath"]');*@
                var navCube = new xNavigationCube();
                navCube.ratio = .15;
                viewer.addPlugin(navCube);
                viewer.start();


        </script>
    </div>

    @*<script>
                viewer.on('pick', function (args) {
                    var id = args.id;
                    viewer.setCameraTarget(id);
                    pickedId = id;
                });
        </script>*@

    @*<script>
        viewer.on('fps', function (fps) {
            var span = document.getElementById('fps');
            if (span) {
                span.innerHTML = "Frames Per Seconf :" + fps;
            }
        });
    </script>

    <div class="container">
        <div>
            <label id="productId"> </label>
            <br />
            <label id="fps"> </label>
        </div>

        <div>
            <input type="text" id="camX" value="-20" />
            <input type="text" id="camY" value="-20" />
            <input type="text" id="camZ" value="20" />
            <button onclick="SetCamera()">Set camera</button>
        </div>

        <script type="text/javascript">
            function SetCamera() {
                if (viewer) {
                    var iX = document.getElementById('camX');
                    var iY = document.getElementById('camY');
                    var iZ = document.getElementById('camZ');
                    viewer.setCameraPosition([iX.value, iY.value, iZ.value]);
                }
            }
        </script>

        <div>
            <button onclick="if (viewer) viewer.show('front');">Front</button>
            <button onclick="if (viewer) viewer.show('back');">Back</button>
            <button onclick="if (viewer) viewer.show('top');">Top</button>
            <button onclick="if (viewer) viewer.show('bottom');">Bottom</button>
            <button onclick="if (viewer) viewer.show('left');">Left</button>
            <button onclick="if (viewer) viewer.show('right');">Right</button>
        </div>

        <div>
            <button onclick="if (viewer) viewer.navigationMode = 'orbit';">Orbit</button>
            <button onclick="if (viewer) viewer.navigationMode = 'free-orbit';">Free orbit</button>
            <button onclick="if (viewer) viewer.navigationMode = 'pan';">Pan</button>
            <button onclick="if (viewer) viewer.navigationMode = 'zoom';">Zoom</button>

            <button onclick="if (viewer) viewer.navigationMode = 'none';">Disable default navigation completely</button>
        </div>


        <div>
            <button onclick="if (viewer) viewer.clip();">Interactive clipping</button>
            <button onclick="if (viewer) viewer.unclip();">Unclip</button>
            <br />
            <input type="text" id="clipOrigX" value="0" />
            <input type="text" id="clipOrigY" value="0" />
            <input type="text" id="clipOrigZ" value="0" />
            <br />
            <input type="text" id="clipNormX" value="-1" />
            <input type="text" id="clipNormY" value="0" />
            <input type="text" id="clipNormZ" value="0" />
            <br />
            <button onclick="Clip()">Clip</button>
            <script type="text/javascript">
                function Clip() {
                    var oX = document.getElementById('clipOrigX').value;
                    var oY = document.getElementById('clipOrigY').value;
                    var oZ = document.getElementById('clipOrigZ').value;

                    var nX = document.getElementById('clipNormX').value;
                    var nY = document.getElementById('clipNormY').value;
                    var nZ = document.getElementById('clipNormZ').value;

                    if (viewer)
                        viewer.clip([oX, oY, oZ], [nX, nY, nZ]);
                }
            </script>
        </div>
        <div>
            <select id="cmbHide">
                <option value="noAction">No action</option>
                <option value="hideProduct">Hide product</option>
                <option value="hideType">Hide type</option>
                <option value="highlight">Highlight</option>
            </select>
            <button onclick="if (viewer) viewer.resetStates()">Show all</button>
            <script type="text/javascript">

                var timer = 0;

                viewer.on('pick', function (args) {
                    var id = args.id;
                    viewer.setCameraTarget(id);
                    pickedId = id;
                    document.getElementById('hiddenId').value = id;
                    var span = document.getElementById('productId');
                    if (span) {
                        span.innerHTML = "Selected Product Id = " + id;
                    }

                    var cmb = document.getElementById('cmbHide');
                    var option = cmb.value;
                    switch (option) {
                        case 'hideProduct':
                            viewer.setState(xState.HIDDEN, [args.id]);
                            break;
                        case 'hideType':
                            var type = viewer.getProductType(args.id);
                            viewer.setState(xState.HIDDEN, type);
                            break;
                        case 'highlight':
                            viewer.setState(xState.HIGHLIGHTED, [args.id]);
                            break;
                        default:
                            break;
                    }

                    var time = (new Date()).getTime();
                    if (time - timer < 200)
                        viewer.zoomTo(id);
                    timer = time;

                });
            </script>
        </div>

        <div>
            Rendering mode
            <label>
                <input type="radio" name="rRenderingMode" checked="checked"
                       onchange="if (viewer) viewer.renderingMode = 'normal';" />
                Normal
            </label>
            <label>
                <input type="radio" name="rRenderingMode"
                       onchange="if (viewer) viewer.renderingMode = 'x-ray';" />
                X-Ray
            </label>
        </div>

        <button onclick="Recolour()">Recolour by type</button>
        <button onclick="if (viewer) viewer.resetStyles();">Reset styles</button>

        <script type="text/javascript">
            function Recolour() {
                if (!viewer) return;
                var index = 0;
                for (var i in xProductType) {
                    var type = xProductType[i];
                    var colour = [Math.random() * 255, Math.random() * 255, Math.random() * 255, 255];
                    viewer.defineStyle(index, colour);
                    viewer.setStyle(index, type);
                    index++;
                }
            };
        </script>

        @using (Html.BeginForm("Modify", "Home", FormMethod.Post, new { id = "myForm" }))
        {
            <input name="hiddenId" type="hidden" id="hiddenId" />
            <input name="newX" type="number" id="newX" />
            <input name="newY" type="number" id="newY" />
            <input type="submit" onclick="SubmitData(event)" value="Modify CrossSection" />

        }

        <script>
            function SubmitData(e) {
                debugger;
                e.preventDefault();


                var pId = document.getElementById("hiddenId").value;
                var newX = document.getElementById("newX").value;
                var newY = document.getElementById("newY").value;
                debugger;

                // Your Logic
                var f = $('#myForm');
                f.submit();


            }
        </script>
        
    </div>*@

</body>
</html>
<style>
    .DownloadContainer {
        background: #e6e6e6
    }
    .footer {
        position: static !important;
        /*margin-top: 100px*/
    }
</style>